package auth

import (
	"context"
	"errors"
	"fmt"
	"time"

	"github.com/tpt-online-video/packages/auth"
)

var (
	ErrEmailAlreadyExists   = errors.New("email already exists")
	ErrInvalidCredentials   = errors.New("invalid email or password")
	ErrUserNotFound         = errors.New("user not found")
	ErrUserSuspended        = errors.New("account is suspended")
	ErrUserBanned           = errors.New("account is banned")
	ErrInvalidRefreshToken  = errors.New("invalid or expired refresh token")
	ErrTokenReuseDetected   = errors.New("refresh token reuse detected")
	ErrPasswordResetExpired = errors.New("password reset token has expired")
	ErrPasswordResetUsed    = errors.New("password reset token already used")
	ErrOAuthEmailMismatch   = errors.New("oauth email does not match existing account")
	ErrInvalidPassword      = errors.New("password does not meet requirements")
)

// ServiceConfig configures the auth service.
type ServiceConfig struct {
	JWTSecret           string
	JWTAccessTTL        time.Duration
	JWTRefreshTTL       time.Duration
	PasswordResetTTL    time.Duration
	EmailVerificationTTL time.Duration
	FrontendBaseURL     string
}

// Service handles authentication business logic.
type Service struct {
	repo        *Repository
	hasher      *auth.PasswordHasher
	tokenMgr    *auth.TokenManager
	emailSender auth.EmailSender
	config      ServiceConfig
}

// NewService creates a new auth service.
func NewService(repo *Repository, emailSender auth.EmailSender, config ServiceConfig) *Service {
	return &Service{
		repo:        repo,
		hasher:      auth.NewPasswordHasher(),
		tokenMgr:    auth.NewTokenManager(),
		emailSender: emailSender,
		config:      config,
	}
}

// RegisterResponse is returned after successful registration.
type RegisterResponse struct {
	User        *User  `json:"user"`
	AccessToken string `json:"access_token"`
	Role        string `json:"role"`
}

// LoginResponse is returned after successful login.
type LoginResponse struct {
	User         *User  `json:"user"`
	AccessToken  string `json:"access_token"`
	RefreshToken string `json:"refresh_token"`
	Role         string `json:"role"`
}

// RefreshResponse is returned after token refresh.
type RefreshResponse struct {
	AccessToken  string `json:"access_token"`
	RefreshToken string `json:"refresh_token"`
}

// ---------- Registration ----------

// Register creates a new user account with email/password.
func (s *Service) Register(ctx context.Context, email, password, displayName string) (*RegisterResponse, error) {
	// Validate password
	if len(password) < 8 {
		return nil, ErrInvalidPassword
	}

	// Check existing user
	existing, err := s.repo.GetUserByEmail(ctx, email)
	if err != nil {
		return nil, fmt.Errorf("check existing user: %w", err)
	}
	if existing != nil {
		return nil, ErrEmailAlreadyExists
	}

	// Hash password
	passwordHash, err := s.hasher.Hash(password)
	if err != nil {
		return nil, fmt.Errorf("hash password: %w", err)
	}

	// Default display name from email if not provided
	if displayName == "" {
		displayName = email[:len(email)-len("@")] // local part of email
	}

	// Create user
	user, err := s.repo.CreateUser(ctx, email, passwordHash, displayName)
	if err != nil {
		return nil, fmt.Errorf("create user: %w", err)
	}

	// Assign default role
	if err := s.repo.AssignDefaultRole(ctx, user.ID); err != nil {
		return nil, fmt.Errorf("assign default role: %w", err)
	}

	// Get the user's role
	roles, _ := s.repo.GetUserRoles(ctx, user.ID)
	role := "user"
	if len(roles) > 0 {
		role = roles[0]
	}

	// Send welcome email (best-effort)
	_ = s.emailSender.SendWelcomeEmail(ctx, email, displayName)

	return &RegisterResponse{
		User: user,
		Role: role,
	}, nil
}

// ---------- Login ----------

// Login authenticates a user with email and password.
func (s *Service) Login(ctx context.Context, email, password string) (*LoginResponse, error) {
	user, err := s.repo.GetUserByEmail(ctx, email)
	if err != nil {
		return nil, fmt.Errorf("get user: %w", err)
	}
	if user == nil {
		return nil, ErrInvalidCredentials
	}

	// Check user status
	switch user.Status {
	case "suspended":
		return nil, ErrUserSuspended
	case "banned":
		return nil, ErrUserBanned
	}

	// Password hash may be nil for OAuth-only accounts
	if user.PasswordHash == nil {
		return nil, ErrInvalidCredentials
	}

	// Verify password
	if !s.hasher.Compare(password, *user.PasswordHash) {
		return nil, ErrInvalidCredentials
	}

	// Generate tokens
	roles, _ := s.repo.GetUserRoles(ctx, user.ID)
	role := "user"
	if len(roles) > 0 {
		role = roles[0]
	}

	// Access token will be generated by middleware.GenerateTokenPair
	// Refresh token (opaque, stored in DB)
	refreshToken, refreshHash, err := s.tokenMgr.NewRandomToken()
	if err != nil {
		return nil, fmt.Errorf("generate refresh token: %w", err)
	}

	rtExpiresAt := time.Now().Add(s.config.JWTRefreshTTL)
	familyID := newUUID()

	if err := s.repo.CreateRefreshToken(ctx, user.ID, refreshHash, familyID, rtExpiresAt); err != nil {
		return nil, fmt.Errorf("store refresh token: %w", err)
	}

	return &LoginResponse{
		User:         user,
		RefreshToken: refreshToken,
		Role:         role,
	}, nil
}

// ---------- Token Refresh ----------

// RefreshTokens validates a refresh token and issues new ones (token rotation).
func (s *Service) RefreshTokens(ctx context.Context, currentRefreshToken string) (*RefreshResponse, error) {
	tokenHash := auth.HashToken(currentRefreshToken)

	stored, err := s.repo.GetRefreshTokenByHash(ctx, tokenHash)
	if err != nil {
		return nil, fmt.Errorf("get refresh token: %w", err)
	}
	if stored == nil {
		return nil, ErrInvalidRefreshToken
	}

	// Check if token has been revoked (token reuse detection)
	if stored.RevokedAt != nil {
		// Token reuse detected! Revoke entire family.
		_ = s.repo.RevokeRefreshTokenFamily(ctx, stored.FamilyID)
		return nil, ErrTokenReuseDetected
	}

	// Check if expired
	if time.Now().After(stored.ExpiresAt) {
		return nil, ErrInvalidRefreshToken
	}

	// Revoke the current token
	if err := s.repo.RevokeRefreshToken(ctx, stored.ID); err != nil {
		return nil, fmt.Errorf("revoke old refresh token: %w", err)
	}

	// Issue new tokens
	newRefreshToken, newRefreshHash, err := s.tokenMgr.NewRandomToken()
	if err != nil {
		return nil, fmt.Errorf("generate new refresh token: %w", err)
	}

	rtExpiresAt := time.Now().Add(s.config.JWTRefreshTTL)
	if err := s.repo.CreateRefreshToken(ctx, stored.UserID, newRefreshHash, stored.FamilyID, rtExpiresAt); err != nil {
		return nil, fmt.Errorf("store new refresh token: %w", err)
	}

	return &RefreshResponse{
		RefreshToken: newRefreshToken,
	}, nil
}

// ---------- Logout ----------

// Logout revokes all refresh tokens for a user.
func (s *Service) Logout(ctx context.Context, userID string) error {
	return s.repo.RevokeAllUserRefreshTokens(ctx, userID)
}

// LogoutSession revokes a specific refresh token.
func (s *Service) LogoutSession(ctx context.Context, userID, refreshTokenHash string) error {
	rt, err := s.repo.GetRefreshTokenByHash(ctx, refreshTokenHash)
	if err != nil {
		return err
	}
	if rt == nil || rt.UserID != userID {
		return nil // Already gone
	}
	return s.repo.RevokeRefreshToken(ctx, rt.ID)
}

// ---------- Password Reset ----------

// RequestPasswordReset generates a password reset token and sends an email.
func (s *Service) RequestPasswordReset(ctx context.Context, email string) error {
	user, err := s.repo.GetUserByEmail(ctx, email)
	if err != nil {
		return fmt.Errorf("get user: %w", err)
	}
	if user == nil {
		// Don't reveal whether the email exists
		return nil
	}

	// Generate reset token
	resetToken, resetHash, err := s.tokenMgr.NewRandomToken()
	if err != nil {
		return fmt.Errorf("generate reset token: %w", err)
	}

	expiresAt := time.Now().Add(s.config.PasswordResetTTL)
	if err := s.repo.CreatePasswordResetToken(ctx, user.ID, resetHash, expiresAt); err != nil {
		return fmt.Errorf("store reset token: %w", err)
	}

	// Build reset URL
	resetURL := fmt.Sprintf("%s/reset-password?token=%s&email=%s",
		s.config.FrontendBaseURL, resetToken, email)

	// Send email (best-effort)
	_ = s.emailSender.SendPasswordResetEmail(ctx, email, resetURL)

	return nil
}

// ResetPassword validates a reset token and updates the password.
func (s *Service) ResetPassword(ctx context.Context, token, newPassword string) error {
	if len(newPassword) < 8 {
		return ErrInvalidPassword
	}

	tokenHash := auth.HashToken(token)

	prt, err := s.repo.GetPasswordResetTokenByHash(ctx, tokenHash)
	if err != nil {
		return fmt.Errorf("get reset token: %w", err)
	}
	if prt == nil {
		return ErrPasswordResetUsed
	}

	// Check expiry
	if time.Now().After(prt.ExpiresAt) {
		return ErrPasswordResetExpired
	}

	// Hash new password
	passwordHash, err := s.hasher.Hash(newPassword)
	if err != nil {
		return fmt.Errorf("hash password: %w", err)
	}

	// Update password
	if err := s.repo.UpdateUserPassword(ctx, prt.UserID, passwordHash); err != nil {
		return fmt.Errorf("update password: %w", err)
	}

	// Mark token as used
	if err := s.repo.MarkPasswordResetTokenUsed(ctx, prt.ID); err != nil {
		return fmt.Errorf("mark token used: %w", err)
	}

	// Revoke all refresh tokens for security
	_ = s.repo.RevokeAllUserRefreshTokens(ctx, prt.UserID)

	return nil
}

// ---------- OAuth ----------

// OAuthProviderInfo holds the configuration for an OAuth provider.
type OAuthProviderInfo struct {
	Name         string `json:"name"`
	ClientID     string `json:"client_id"`
	AuthURL      string `json:"auth_url"`
	TokenURL     string `json:"token_url"`
	UserInfoURL  string `json:"user_info_url"`
	Scopes       string `json:"scopes"`
	RedirectURI  string `json:"redirect_uri"`
}

// OAuthUserInfo represents the user information returned by an OAuth provider.
type OAuthUserInfo struct {
	Provider          string
	ProviderAccountID string
	Email             string
	DisplayName       string
}

// OAuthLoginOrRegister handles OAuth login or registration.
// If the OAuth account exists, it logs the user in.
// If not, it creates a new user or links to an existing one.
func (s *Service) OAuthLoginOrRegister(ctx context.Context, info *OAuthUserInfo) (*LoginResponse, error) {
	// Check if this OAuth account is already linked
	oa, err := s.repo.GetOAuthAccount(ctx, info.Provider, info.ProviderAccountID)
	if err != nil {
		return nil, fmt.Errorf("get oauth account: %w", err)
	}

	if oa != nil {
		// Account exists, log in as the linked user
		user, err := s.repo.GetUserByID(ctx, oa.UserID)
		if err != nil {
			return nil, fmt.Errorf("get user: %w", err)
		}
		if user == nil {
			return nil, ErrUserNotFound
		}
		if user.Status == "suspended" {
			return nil, ErrUserSuspended
		}
		if user.Status == "banned" {
			return nil, ErrUserBanned
		}

		roles, _ := s.repo.GetUserRoles(ctx, user.ID)
		role := "user"
		if len(roles) > 0 {
			role = roles[0]
		}

		refreshToken, refreshHash, err := s.tokenMgr.NewRandomToken()
		if err != nil {
			return nil, fmt.Errorf("generate refresh token: %w", err)
		}
		rtExpiresAt := time.Now().Add(s.config.JWTRefreshTTL)
		familyID := newUUID()
		if err := s.repo.CreateRefreshToken(ctx, user.ID, refreshHash, familyID, rtExpiresAt); err != nil {
			return nil, fmt.Errorf("store refresh token: %w", err)
		}

		return &LoginResponse{
			User:         user,
			RefreshToken: refreshToken,
			Role:         role,
		}, nil
	}

	// No existing OAuth link. Check if a user with this email exists.
	existingUser, err := s.repo.GetUserByEmail(ctx, info.Email)
	if err != nil {
		return nil, fmt.Errorf("get user by email: %w", err)
	}

	var userID string
	if existingUser != nil {
		// Link OAuth to existing user
		userID = existingUser.ID
		if err := s.repo.LinkOAuthToUser(ctx, userID, info.Provider, info.ProviderAccountID, &info.Email); err != nil {
			return nil, fmt.Errorf("link oauth to user: %w", err)
		}
	} else {
		// Create new user with OAuth
		email := info.Email
		passwordHash := (*string)(nil) // No password for OAuth-only accounts
		user, err := s.repo.CreateUser(ctx, email, "", info.DisplayName)
		if err != nil {
			return nil, fmt.Errorf("create oauth user: %w", err)
		}
		userID = user.ID

		_ = passwordHash // user has no password

		// Verify email since OAuth providers verify emails
		if err := s.repo.VerifyUserEmail(ctx, userID); err != nil {
			return nil, fmt.Errorf("verify email: %w", err)
		}

		if err := s.repo.AssignDefaultRole(ctx, userID); err != nil {
			return nil, fmt.Errorf("assign default role: %w", err)
		}

		// Link OAuth account
		if err := s.repo.CreateOAuthAccount(ctx, userID, info.Provider, info.ProviderAccountID, &info.Email); err != nil {
			return nil, fmt.Errorf("create oauth account: %w", err)
		}
	}

	user, err := s.repo.GetUserByID(ctx, userID)
	if err != nil {
		return nil, fmt.Errorf("get user: %w", err)
	}

	roles, _ := s.repo.GetUserRoles(ctx, userID)
	role := "user"
	if len(roles) > 0 {
		role = roles[0]
	}

	refreshToken, refreshHash, err := s.tokenMgr.NewRandomToken()
	if err != nil {
		return nil, fmt.Errorf("generate refresh token: %w", err)
	}
	rtExpiresAt := time.Now().Add(s.config.JWTRefreshTTL)
	familyID := newUUID()
	if err := s.repo.CreateRefreshToken(ctx, userID, refreshHash, familyID, rtExpiresAt); err != nil {
		return nil, fmt.Errorf("store refresh token: %w", err)
	}

	return &LoginResponse{
		User:         user,
		RefreshToken: refreshToken,
		Role:         role,
	}, nil
}

// ---------- Session ----------

// GetActiveSessions returns all active refresh tokens for a user.
func (s *Service) GetActiveSessions(ctx context.Context, userID string) ([]*RefreshToken, error) {
	// We query all non-revoked, non-expired tokens
	rows, err := s.repo.DB().Query(ctx,
		`SELECT id, user_id, family_id, expires_at, created_at
		 FROM refresh_tokens
		 WHERE user_id = $1 AND revoked_at IS NULL AND expires_at > now()
		 ORDER BY created_at DESC`,
		userID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var sessions []*RefreshToken
	for rows.Next() {
		rt := &RefreshToken{}
		if err := rows.Scan(&rt.ID, &rt.UserID, &rt.FamilyID, &rt.ExpiresAt, &rt.CreatedAt); err != nil {
			return nil, err
		}
		sessions = append(sessions, rt)
	}
	return sessions, nil
}

// RevokeSession revokes a specific session by ID.
func (s *Service) RevokeSession(ctx context.Context, userID, sessionID string) error {
	return s.repo.RevokeRefreshToken(ctx, sessionID)
}

// StoreRefreshToken stores a refresh token in the database.
func (s *Service) StoreRefreshToken(ctx context.Context, userID, tokenHash string, expiresAt time.Time) error {
	familyID := newUUID()
	return s.repo.CreateRefreshToken(ctx, userID, tokenHash, familyID, expiresAt)
}

// GetRefreshTokenData returns refresh token data by hash without performing rotation.
func (s *Service) GetRefreshTokenData(ctx context.Context, tokenHash string) (*RefreshToken, error) {
	return s.repo.GetRefreshTokenByHash(ctx, tokenHash)
}

// GetMe returns the current user by ID.
func (s *Service) GetMe(ctx context.Context, userID string) (*User, error) {
	return s.repo.GetUserByID(ctx, userID)
}

// GetRoles returns the roles for a user.
func (s *Service) GetRoles(ctx context.Context, userID string) ([]string, error) {
	return s.repo.GetUserRoles(ctx, userID)
}
